#!/usr/bin/env bash
# bash script for nginx installation
sudo apt-get -y update
sudo apt-get -y install nginx
sudo echo "Holberton School" | sudo tee /var/www/html/index.html
sed -i 's/server_name _;/server_name _;\n\trewrite ^\/redirect_me http:\/\/jairofernandosb.tech permanent;/' /etc/nginx/sites-available/default
sudo service nginx start
