#!/usr/bin/env  bash
# script that sets a coustom header for nginx
sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
sudo sed -i '43a\    location \/ {\n        try_files $uri $uri\/ =404;\n    }\n    error_page 404 /404.html;' /etc/nginx/sites-available/default
sudo sed -i '45a\        add_header X-Served-By $HOSTNAME;' /etc/nginx/sites-available/default
sudo service nginx restart
