#!/usr/bin/env bash
# create a general backup for all databases on mysql

DATE=$(date +'%d-%m-%Y')
export MYSQL_PWD=$1
DATABASES=$(mysql -uroot -h localhost -e "SHOW DATABASES;" | tr -d "| " | grep -v Database)

for db in $DATABASES;
do
    if [[ "$db" != "information_schema" ]] &&
        [[ "$db" != "performance_schema" ]] &&
        [[ "$db" != "mysql" ]] &&
        [[ "$db" != _* ]];
    then
            mysqldump -uroot -h localhost --databases "$db" >> backup.sql
    fi
done

sudo tar -czf "$DATE".tar.gz backup.sql
