#!/usr/bin/env bash
# create a general backup for all databases on mysql
DATE=$(date +'%d-%m-%Y')
export MYSQL_PWD=$1
mysqldump -uroot --all-databases > backup.sql
sudo tar -czf "$DATE".tar.gz backup.sql
