#!/usr/bin/env bash
# advanced task
sudo touch /var/run/holbertonscript.pid
sudo chmod 777 /var/run/holbertonscript.pid
echo $$ > /var/run/holbertonscript.pid
while true
do
    echo "To infinity and beyond"
    trap "echo Y U no love me?!" 2
    trap "echo I hate the kill command; sudo rm /var/run/holbertonscript.pid" 3 15
done
