#!/usr/bin/env bash
# Bash script that displays Holberton School 10 times,
# but for the 9th iteration, displays Holberton School and then Hi on a new line.
for i in {1..10}
do
    if [ $i -eq 9 ]
        then
            echo "Hi"
        else
            echo "Holberton School"
    fi
done
