#!/usr/bin/env bash
# Bash script that displays Holberton School 10 times,
# but for the 9th iteration, displays Holberton School and then Hi on a new line.
for i in 1 2 3 4 5 6 7 8 9 10
do
    if [ $i -eq 9 ]
        then
            echo "hi"
        else
            echo "holberton School"
    fi
done
