#!/usr/bin/env bash
#  Bash script that displays numbers from 1 to 20 and:
#  displays 4 and then bad luck from China for the 4th loop iteration
#  displays 9 and then bad luck from Japan for the 9th loop iteration
#  displays 17 and then bad luck from Italy for the 17th loop iteration
for i in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20
do
    echo $i
    if [ $i -eq 4 ]
        then
            echo "bad luck from China"
    elif [ $i -eq 9 ]
        then
            echo "bad luck from Japan"
    elif [ $i -eq 17 ]
        then
            echo "bad luck from Italy"
    fi
done
