#!/usr/bin/env bash
# Bash script that gives you information about the holbertonschool file.
file="holbertonschool"
if [ -e "$file" ]
then
    echo "file exists"
    if [ -s "$file" ]
    then
        echo "file is not empty"
    else
        echo "file is empty"
    fi
    if [ -f "$file" ]
    then
        echo "is a regular file"
    fi
else
    echo "file does not exist"
fi
