#!/usr/bin/env bash
# Bash script that configures an Ubuntu server it's on docker
sudo cp /etc/hosts ~/hosts.new
sudo sed -i "s/127.0.0.1/127.0.0.2/" ~/hosts.new
sudo echo "8.8.8.8       facebook.com" >> ~/hosts.new
sudo cp -f ~/hosts.new /etc/hosts
